#+TITLE: GNU Emacs (config files)
#+AUTHOR: Maximiliano Christener
#+STARTUP: overview
#+OPTIONS: toc:2

* Índice :TOC:
- [[#intro][Intro]]
  - [[#sobre-org-mode][Sobre Org Mode]]
- [[#config][Config]]
  - [[#general-confs][General confs]]
  - [[#python][Python]]
  - [[#magit][Magit]]
  - [[#keybindings][Keybindings]]
  - [[#terminal][Terminal]]
  - [[#marginalia][Marginalia]]
  - [[#org-mode][Org Mode]]
  - [[#completion-company-mode][Completion: Company mode]]
  - [[#tree-sitter-integration][Tree-sitter Integration]]
  - [[#dired][Dired]]
  - [[#evil-mode][Evil Mode]]

* Intro
** Sobre Org Mode

Los modos son
- =C-c C-x a= para archivar
- =C-c TAB= para abrir el árbol
- =C-c o= para ir a un lugar determinado
  desde la toc.

*** Expansions in Org-Tempo

Org-tempo agrega un snippet para escribir bloques en Org. A saber,

| Typing the below + TAB | Expands to ...                          |
|------------------------+-----------------------------------------|
| <a                     | '#+BEGIN_EXPORT ascii' … '#+END_EXPORT  |
| <c                     | '#+BEGIN_CENTER' … '#+END_CENTER'       |
| <C                     | '#+BEGIN_COMMENT' … '#+END_COMMENT'     |
| <e                     | '#+BEGIN_EXAMPLE' … '#+END_EXAMPLE'     |
| <E                     | '#+BEGIN_EXPORT' … '#+END_EXPORT'       |
| <h                     | '#+BEGIN_EXPORT html' … '#+END_EXPORT'  |
| <l                     | '#+BEGIN_EXPORT latex' … '#+END_EXPORT' |
| <q                     | '#+BEGIN_QUOTE' … '#+END_QUOTE'         |
| <s                     | '#+BEGIN_SRC' … '#+END_SRC'             |
| <v                     | '#+BEGIN_VERSE' … '#+END_VERSE'         |


* Config

** General confs
#+begin_src emacs-lisp
  (load-theme 'modus-vivendi)
  ;; When Delete Selection mode is enabled, typed text replaces the selection
  ;; if the selection is active.
  (delete-selection-mode 1)
  ;; Display the current line and column numbers in the mode line
  (setq line-number-mode t)
  (setq column-number-mode t)
  (setq mode-line-position-column-line-format '("%l:%C"))

  ;; Display of line numbers in the buffer:
  (setq-default display-line-numbers-type 'relative)
  (dolist (hook '(prog-mode-hook text-mode-hook conf-mode-hook))
    (add-hook hook #'display-line-numbers-mode))

  ;; packages
  (setq package-pinned-packages
      '((annalist                      . "melpa-stable")
        (ansible-doc                   . "melpa-stable")
        (apheleia                      . "melpa-stable")
        (basic-mode                    . "melpa-stable")
        (consult-dir                   . "melpa-stable")
        (corfu-prescient               . "melpa-stable")
        (dtrt-indent                   . "melpa-stable")
        (dumb-jump                     . "melpa-stable")
        (elisp-refs                    . "melpa-stable")
        (evil-collection               . "melpa-stable")
        (f                             . "melpa-stable")
        (flymake-quickdef              . "melpa-stable")
        (groovy-mode                   . "melpa-stable")
        (highlight-defined             . "melpa-stable")
        (markdown-toc                  . "melpa-stable")
        (org-appear                    . "melpa-stable")
        (package-lint-flymake          . "melpa-stable")
        (parent-mode                   . "melpa-stable")
        (php-mode                      . "melpa-stable")
        (prescient                     . "melpa-stable")
        (s                             . "melpa-stable")
        (tocus                         . "melpa-stable")
        (treesit-auto                  . "melpa-stable")
        (vertico-prescient             . "melpa-stable")
        (visual-fill-column            . "melpa-stable")
        (yasnippet-snippets            . "melpa-stable")
        (ace-window                    . "gnu")
        (aggressive-indent             . "gnu")
        (avy                           . "gnu")
        (cape                          . "gnu")
        (compat                        . "gnu")
        (consult                       . "gnu")
        (corfu                         . "gnu")
        (csv-mode                      . "gnu")
        (dash                          . "gnu")
        (diff-hl                       . "gnu")
        (diminish                      . "gnu")
        (easy-escape                   . "gnu")
        (embark                        . "gnu")
        (embark-consult                . "gnu")
        (expand-region                 . "gnu")
        (gcmh                          . "gnu")
        (indent-bars                   . "gnu")
        (marginalia                    . "gnu")
        (modus-themes                  . "gnu")
        (orderless                     . "gnu")
        (org                           . "gnu")
        (rainbow-mode                  . "gnu")
        (transient                     . "gnu")
        (vertico                       . "gnu")
        (yasnippet                     . "gnu")
        (ztree                         . "gnu")
        (eat                           . "nongnu")
        (edit-indirect                 . "nongnu")
        (evil-visualstar               . "nongnu")
        (exec-path-from-shell          . "nongnu")
        (git-modes                     . "nongnu")
        (golden-ratio                  . "nongnu")
        (goto-chg                      . "nongnu")
        (gptel                         . "nongnu")
        (lua-mode                      . "nongnu")
        (magit                         . "nongnu")
        (markdown-mode                 . "nongnu")
        (package-lint                  . "nongnu")
        (page-break-lines              . "nongnu")
        (paredit                       . "nongnu")
        (popup                         . "nongnu")
        (rainbow-delimiters            . "nongnu")
        (undo-fu                       . "nongnu")
        (undo-fu-session               . "nongnu")
        (wgrep                         . "nongnu")
        (with-editor                   . "nongnu")
        (ws-butler                     . "nongnu")
        (yaml-mode                     . "nongnu")))
#+end_src

** Python
#+begin_src emacs-lisp
  ;; python
  (use-package uv-mode
    :ensure t
    :hook (python-mode . uv-mode-auto-activate-hook))
  (add-hook 'python-mode-hook #'electric-pair-mode)
#+end_src
** Magit
#+begin_src emacs-lisp
  (use-package magit
    :ensure t)
#+end_src

** Keybindings
#+begin_src emacs-lisp
;; e.g. (keymap-set c-mode-map "C-S-l" 'function-name)
(keymap-global-set "C-x C-a" #'auto-fill-mode)
(keymap-global-set "C-x v t" #'vterm)
#+end_src

** Terminal
#+begin_src emacs-lisp
  ;;; vterm
  (use-package vterm
    :ensure t
    :init 
    (setq vterm-shell "/bin/zsh"))

  ;; eshell
  (use-package eshell-syntax-highlighting
    :ensure t
    :after esh-mode
    :config
    (eshell-syntax-highlighting-global-mode +1))
  ;; eshell-syntax-highlighting -- adds fish/zsh-like syntax highlighting.

  ;; eshell-rc-script -- your profile for eshell; like a bashrc for eshell.
  ;; eshell-aliases-file -- sets an aliases file for the eshell.
  (setq ;;eshell-rc-script (concat user-emacs-directory "eshell/profile")
   ;;eshell-aliases-file (concat user-emacs-directory "eshell/aliases")
   eshell-history-size 5000
   eshell-buffer-maximum-lines 5000
   eshell-hist-ignoredups t
   eshell-scroll-to-bottom-on-input t
   eshell-destroy-buffer-when-process-dies t
   eshell-visual-commands'("bash" "fish" "htop" "ssh" "top" "zsh"))
#+end_src
** Marginalia
#+begin_src emacs-lisp
  (use-package marginalia
    :ensure t
    ;; Bind `marginalia-cycle' locally in the minibuffer.  To make the binding
    ;; available in the *Completions* buffer, add it to the
    ;; `completion-list-mode-map'.
    :bind (:map minibuffer-local-map
           ("M-A" . marginalia-cycle))
    ;; The :init section is always executed.
    :init
    ;; Marginalia must be activated in the :init section of use-package such that
    ;; the mode gets enabled right away. Note that this forces loading the
    ;; package.
    (marginalia-mode))
#+end_src
** Org Mode
Emacs todavía existe gracias a Org Mode. Una lástima que no se haya
convertido en un estándar como Markdown
#+BEGIN_SRC emacs-lisp
  ;; Para usar extensiones (<a <s etc)
  (require 'org-tempo)

  ;;; Bullets
  (use-package org-bullets
    :ensure t)
  (add-hook 'org-mode-hook
  	  (lambda () (org-bullets-mode 1)))

  ;;; Appearance
  ;; (add-hook 'org-mode-hook 'variable-pitch-mode)
  ;; (custom-theme-set-faces
  ;;  'user
  ;;  '(variable-pitch ((t (:family "SauceCodePro NF" :height 180))))
  ;;  '(fixed-pitch ((t (:family "SauceCodePro NF" :height 160)))))
  ;; colores
  ;; (setq org
  ;;       -format-latex-options (plist-put org-format-latex-options :scale 2.4)
  ;;       org-hide-emphasis-markers t
  ;;       header-line-format nil
  ;;       org-emphasis-alist
  ;;        '(("*" (bold :foreground "Orange"))
  ;;         ("/" (italic :foreground "Green"))
  ;;         ("_" underline)
  ;;         ("=" (:background "maroon" :foreground "white"))
  ;;         ("~" (:background "deep sky blue" :foreground "MidnightBlue"))
  ;;         ("+" (:strike-through t))))
  ;; ;; pure lisp magic :D
  ;; (dolist (face '((org-level-1 . 1.2)
  ;;                 (org-level-2 . 1.1)
  ;;                 (org-level-3 . 1.05)
  ;;                 (org-level-4 . 1.0)
  ;;                 (org-level-5 . 1.1)
  ;;                 (org-level-6 . 1.1)
  ;;                 (org-level-7 . 1.1)
  ;;                 (org-level-8 . 1.1)))
  ;;   (set-face-attribute (car face) nil
  ;;                       :font "SauceCodePro NF"
  ;;                       :weight 'medium
  ;;                       :height (cdr face))) 

  ;;; TOC
  (use-package toc-org
    :ensure t
    :commands toc-org-enable)
  (add-hook 'org-mode-hook 'toc-org-enable)


  ;; org indent                         
  ;; (add-hook 'org-mode-hook 'org-indent-mode)

  ;;; Presentations
  ;; (use-package org-tree-slide
  ;;   :ensure t :custom (org-image-actual-width nil))
  ;; (add-hook 'org-tree-slide-mode-hook (lambda () (display-line-numbers-mode 0)))
  ;; ;;(setq-default header-line-format " ")
  ;; ;; Para ver en html
  ;; (use-package ox-reveal
  ;;   :ensure t)
#+END_SRC

** Completion: Company mode
#+begin_src emacs-lisp
  ;;; company-mode
  (use-package company
   :ensure t
   :config (add-hook 'after-init-hook 'global-company-mode)
  (setq company-idle-delay 0)
  (setq company-minimum-prefix-length 2)
  (setq company-show-numbers t)
  ;; To prevent default down-casing.
  ;; https://emacs.stackexchange.com/questions/10837/how-to-make-company-mode-be-case-sensitive-on-plain-text
  (setq company-dabbrev-downcase nil)
  (setq company-dabbrev-ignore-case nil)
  (setq company-dabbrev-code-ignore-case nil))
  ;; enable company everywhere
  (add-hook 'after-init-hook 'global-company-mode)
#+end_src

** Tree-sitter Integration

Tree-sitter is an incremental parsing system introduced in Emacs 29 that
provides precise, high-performance syntax analysis and highlighting by
constructing concrete syntax trees from source code. It supports a broad set of
programming languages, including Bash, C, C++, C#, CMake, CSS, Dockerfile, Go,
Java, JavaScript, JSON, Python, Rust, TOML, TypeScript, YAML, Elisp, Lua,
Markdown, and many others. Unlike traditional font-lock, which relies on regular
expressions, Tree-sitter uses formal grammar definitions to build real-time
parse trees, enabling accurate syntax highlighting, structural navigation, code
folding, and foundational support for advanced editing features like
refactoring.

The configuration below enables Tree-sitter support using the treesit-auto
package. Setting treesit-auto-add-to-auto-mode-alist to 'all ensures that all
available Tree-sitter modes are automatically activated for their corresponding
file types. Enabling global-treesit-auto-mode applies this behavior globally,
improving syntax accuracy and consistency across supported languages.
#+begin_src emacs-lisp
(use-package treesit-auto
  :ensure t
  :custom
  (treesit-auto-install 'prompt)
  :config
  (treesit-auto-add-to-auto-mode-alist 'all)
  (global-treesit-auto-mode))
#+end_src

** COMMENT Native compilation
#+begin_src emacs-lisp
;; Native compilation enhances Emacs performance by converting Elisp code into
;; native machine code, resulting in faster execution and improved
;; responsiveness.
;;
;; Ensure adding the following compile-angel code at the very beginning
;; of your `~/.emacs.d/post-init.el` file, before all other packages.
(use-package compile-angel
  :demand t
  :ensure t
  :custom
  ;; Set `compile-angel-verbose` to nil to suppress output from compile-angel.
  ;; Drawback: The minibuffer will not display compile-angel's actions.
  (compile-angel-verbose t)

  :config
  ;; The following directive prevents compile-angel from compiling your init
  ;; files. If you choose to remove this push to `compile-angel-excluded-files'
  ;; and compile your pre/post-init files, ensure you understand the
  ;; implications and thoroughly test your code. For example, if you're using
  ;; the `use-package' macro, you'll need to explicitly add:
  ;; (eval-when-compile (require 'use-package))
  ;; at the top of your init file.
  (push "/init.el" compile-angel-excluded-files)
  (push "/early-init.el" compile-angel-excluded-files)
  (push "/pre-init.el" compile-angel-excluded-files)
  (push "/post-init.el" compile-angel-excluded-files)
  (push "/pre-early-init.el" compile-angel-excluded-files)
  (push "/post-early-init.el" compile-angel-excluded-files)

  ;; A local mode that compiles .el files whenever the user saves them.
  ;; (add-hook 'emacs-lisp-mode-hook #'compile-angel-on-save-local-mode)

  ;; A global mode that compiles .el files prior to loading them via `load' or
  ;; `require'. Additionally, it compiles all packages that were loaded before
  ;; the mode `compile-angel-on-load-mode' was activated.
  (compile-angel-on-load-mode 1))
#+end_src
** Dired
Configuraciones para dired
#+begin_src emacs-lisp
  ;;; Dired
  (with-eval-after-load 'dired
    (require 'dired-x)
      ;; Set dired-x global variables here. For example: (setq dired-x-hands-off-my-keys nil)
      )

  (setq dired-listing-switches
  	      "-lta --dired --group-directories-first -h -G" ;; lt es ordenado por tiempo
  	      dired-dwim-target t
  	      dired-guess-shell-alist-user
  	      '(("\\.\\(png\\|jpe?g\\|tiff\\)" "sxiv" "xdg-open") ; abrir con ! o &
              ("\\.\\(mp[34]\\|m4a\\|ogg\\|flac\\|webm\\|mkv\\)" "mpv" "xdg-open")
  		(".pdf" "rifle")
  		(".*" "xdg-open"))
  	      dired-omit-files "^\\."
  	      dired-kill-when-opening-new-dired-buffer t)
  (add-hook 'dired-mode-hook
  	  'dired-omit-mode)
  ;; (add-hook 'dired-mode-hook
  ;;      'all-the-icons-dired-mode)
#+end_src
** Evil Mode
Como prerequisito, undo-fu
#+begin_src emacs-lisp
  ;; The undo-fu package is a lightweight wrapper around Emacs' built-in undo
  ;; system, providing more convenient undo/redo functionality.
  (use-package undo-fu
    :ensure t
    :commands (undo-fu-only-undo
               undo-fu-only-redo
               undo-fu-only-redo-all
               undo-fu-disable-checkpoint)
    :config
    (global-unset-key (kbd "C-z"))
    (global-set-key (kbd "C-z") 'undo-fu-only-undo)
    (global-set-key (kbd "C-S-z") 'undo-fu-only-redo))

  ;; The undo-fu-session package complements undo-fu by enabling the saving
  ;; and restoration of undo history across Emacs sessions, even after restarting.
  (use-package undo-fu-session
    :ensure t
    :commands undo-fu-session-global-mode
    :hook (after-init . undo-fu-session-global-mode))
#+end_src

Agora sim
#+begin_src emacs-lisp
  (setq evil-default-state 'emacs)
  (setq evil-undo-system 'undo-fu)

  ;; Vim emulation
  (use-package evil
    :ensure t
    :commands (evil-mode evil-define-key)
    :hook (after-init . evil-mode)

    :init
    ;; It has to be defined before evil
    (setq evil-want-integration t)
    (setq evil-want-keybinding nil)

    :custom
    ;; Make :s in visual mode operate only on the actual visual selection
    ;; (character or block), instead of the full lines covered by the selection
    (evil-ex-visual-char-range t)
    ;; Use Vim-style regular expressions in search and substitute commands,
    ;; allowing features like \v (very magic), \zs, and \ze for precise matches
    (evil-ex-search-vim-style-regexp t)
    ;; Enable automatic horizontal split below
    (evil-split-window-below t)
    ;; Enable automatic vertical split to the right
    (evil-vsplit-window-right t)
    ;; Disable echoing Evil state to avoid replacing eldoc
    (evil-echo-state nil)
    ;; Do not move cursor back when exiting insert state
    (evil-move-cursor-back nil)
    ;; Make `v$` exclude the final newline
    (evil-v$-excludes-newline t)
    ;; Allow C-h to delete in insert state
    (evil-want-C-h-delete t)
    ;; Enable C-u to delete back to indentation in insert state
    (evil-want-C-u-delete t)
    ;; Enable C-u to scroll back in normal mode
    (evil-want-C-u-scroll t)
    ;; Enable fine-grained undo behavior
    (evil-want-fine-undo t)
    ;; Allow moving cursor beyond end-of-line in visual block mode
    (evil-move-beyond-eol t)
    ;; Disable wrapping of search around buffer
    (evil-search-wrap nil)
    ;; Whether Y yanks to the end of the line
    (evil-want-Y-yank-to-eol t))

  ;; (use-package evil-collection
  ;;   :after evil
  ;;   :ensure t
  ;;   :init
  ;;   ;; It has to be defined before evil-colllection
  ;;   (setq evil-collection-setup-minibuffer t)
  ;;   :config
  ;;   (evil-collection-init))
#+end_src
